### ISSUE TITLE
Thread panicked when creating mapped buffer

### ISSUE THREAD

**Issue by shazz** [almarklein/wgpu-py#105]
Hi,
Instead of the dummy cube texture I tried to use a real image (1024x1024 RGBA) and it crashes when trying to create the mapped buffer:

```python
self.console.log("Creating Texture")
texture_buffer_object = self.device.create_texture(
    size=texture_size,
    usage=wgpu.TextureUsage.COPY_DST | wgpu.TextureUsage.SAMPLED,
    dimension=wgpu.TextureDimension.d2,
    format=wgpu.TextureFormat.r8uint,
    mip_level_count=1,
    sample_count=1,
)

self.console.log("Creating Texture View")
self.console.log("-- Texture size: {} texture_size: {}".format(texture_data.nbytes, texture_size))

texture_view = texture_buffer_object.create_view()
self.console.log("-- Creating mapped buffer")
tmp_buffer = self.device.create_buffer_mapped(
    size=texture_data.nbytes, 
    usage=wgpu.BufferUsage.COPY_SRC
)    
``` 

Trace:
```
           Creating Texture                                                                                                                                                     WGPUHelper.py:154
           Creating Texture View                                                                                                                                                WGPUHelper.py:164
           -- Texture size: 4194304 texture_size: (4096, 1024, 1)                                                                                                               WGPUHelper.py:167
           -- Creating mapped buffer                                                                                                                                            WGPUHelper.py:170
thread '<unnamed>' panicked at 'assertion failed: size <= self.linear_size', <::std::macros::panic macros>:2:4
stack backtrace:
   0:     0x7f8edb15df44 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7f8edb15df44 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7f8edb15df44 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7f8edb15df44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f8edb178edc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x7f8edb15c8d7 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x7f8edb15fb65 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f8edb15fb65 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f8edb15fb65 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x7f8edb15f851 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x7f8edb16014a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x7f8edb10f30e - std::panicking::begin_panic::h5ff0047d973e6d39
  12:     0x7f8edb101636 - <gfx_memory::allocator::linear::LinearAllocator<B> as gfx_memory::allocator::Allocator<B>>::alloc::hbde26216c4096237
  13:     0x7f8edb0d12d0 - gfx_memory::heaps::memory_type::MemoryType<B>::alloc::hfc4604eab2128fce
  14:     0x7f8edb100d20 - gfx_memory::heaps::Heaps<B>::allocate::ha7ea60b7a1f69861
  15:     0x7f8edb0e7627 - wgpu_core::device::Device<B>::create_buffer::hb40f09283e8f5fd9
  16:     0x7f8edb0bb0aa - wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_buffer_mapped::h2ec40bca1b2f7f4e
  17:     0x7f8edb0d5ddf - wgpu_device_create_buffer_mapped
  18:     0x7f8edb612dec - ffi_call_unix64
  19:     0x7f8edb611f55 - ffi_call
  20:     0x7f8edb834d96 - cdata_call
                               at c/_cffi_backend.c:3148
  21:           0x5c9f63 - _PyObject_FastCallKeywords
  22:           0x535a11 - <unknown>
  23:           0x53c5a1 - _PyEval_EvalFrameDefault
  24:           0x536f27 - _PyEval_EvalCodeWithName
  25:           0x5c9468 - _PyFunction_FastCallKeywords
  26:           0x535880 - <unknown>
  27:           0x5394e1 - _PyEval_EvalFrameDefault
  28:           0x5365e7 - _PyEval_EvalCodeWithName
  29:           0x5c9468 - _PyFunction_FastCallKeywords
  30:           0x535880 - <unknown>
  31:           0x5394e1 - _PyEval_EvalFrameDefault
  32:           0x5365e7 - _PyEval_EvalCodeWithName
  33:           0x5c9468 - _PyFunction_FastCallKeywords
  34:           0x535880 - <unknown>
  35:           0x538713 - _PyEval_EvalFrameDefault
  36:           0x5c916b - _PyFunction_FastCallKeywords
  37:           0x535880 - <unknown>
  38:           0x538713 - _PyEval_EvalFrameDefault
  39:           0x5365e7 - _PyEval_EvalCodeWithName
  40:           0x64cbb3 - PyEval_EvalCode
  41:           0x6402a3 - <unknown>
  42:           0x640357 - PyRun_FileExFlags
  43:           0x64110a - PyRun_SimpleFileExFlags
  44:           0x678eff - <unknown>
  45:           0x6791ee - _Py_UnixMain
  46:     0x7f8ee2c311e3 - __libc_start_main
  47:           0x5cf93e - _start
  48:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted
``` 

Looks it is due to the data size (4194304 bytes) but I did not find the assertion `size <= self.linear_size` in the rust codebase (not sure in which repo to look at)
This one? https://github.com/gfx-rs/gfx-extras/blob/master/gfx-memory/src/allocator/linear.rs#L217

I tried with a smaller image (512x512x4), it did not crash.

Thanks!

**Comment by shazz** [comment]
Unfortunately, with a smaller texture... it crashes a few lines after:

```python

self.console.log("-- Copying data")
ctypes.memmove(
    ctypes.addressof(tmp_buffer.mapping), 
    texture_data.ctypes.data, 
    texture_data.nbytes,
)
tmp_buffer.unmap()

self.console.log("Creating Command Encoder")
command_encoder = self.device.create_command_encoder()

self.console.log("Copy buffer to texture")
command_encoder.copy_buffer_to_texture(
    {
        "buffer": tmp_buffer,
        "offset": 0,
        "bytes_per_row": 4, #texture_data.strides[0],
        "rows_per_image": 0,
    },
    {"texture": texture_view, "mip_level": 0, "array_layer": 0, "origin": (0, 0, 0),},
    copy_size=texture_size,
)
``` 

trace:
```
           -- Copying data                                                                                                                                                      WGPUHelper.py:175
           Creating Command Encoder                                                                                                                                             WGPUHelper.py:183
           Copy buffer to texture                                                                                                                                               WGPUHelper.py:186
Fatal Python error: PyEval_SaveThread: NULL tstate

Current thread 0x00007fd1cd7d4740 (most recent call first):
  File "/home/shazz/projects/games/wgpu-pygame/.venv37/lib/python3.7/site-packages/wgpu/backends/rs.py", line 1118 in copy_buffer_to_texture
```

looks to be at : 
```python
        _lib.wgpu_command_encoder_copy_buffer_to_texture(
            self._internal, c_source, c_destination, c_copy_size[0],
        )
```

**Comment by shazz** [comment]
After some tests, it seems the 2nd bug is linked to `wgpu.TextureFormat.rgba8uint` texture format, with a `wgpu.TextureFormat.r8uint` grayscale texture I don't have the bug.

**Comment by shazz** [comment]
Side question, for a texture in RGBA format (1 byte per component), what should be the texture format? `rgba8uint` ? 

Thanks!

**Comment by almarklein** [comment]
Yeah, I ran into this too. The apparently was an (unintended) limitation in wgpu-core. It has been fixed, but we're still using a version that has this constrained. This should be fixed when we update the wgpu-native lib :)

**Comment by almarklein** [comment]
> Side question, for a texture in RGBA format (1 byte per component), what should be the texture format? rgba8uint ?

Either `rgba8uint` or `rgba8unorm`. In the first case, your data becomes an int 0..255 in the shader. In the latter it becomes a float 0..1.

**Comment by shazz** [comment]
Ok thanks! I will wait for the next release so :)
I'm still wondering why the pipeline is configured using: 

```python
            color_states=[
                {
                    "format": wgpu.TextureFormat.bgra8unorm_srgb,
```
But that's another question :)

**Comment by almarklein** [comment]
You mean `bgra8unorm_srgb` as opposed to e.g. `rgba8uint`?

**Comment by shazz** [comment]
yes...

**Comment by almarklein** [comment]
The `bgra` order appears to be the order that the framebuffer expects. I was a bit surprised about this too. the `srgb` is [a colorspace](https://en.wikipedia.org/wiki/SRGB) meant for displaying something on screen.
